config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcom/index'

  get 'stats/index'
  get 'stats/show'

  resources :articles do
    resources :comments
  end

  root 'welcom#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.order(params[:sort])
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(
      comment_params.merge(
        {
          user: current_user,
        }
      )
    )
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
  end

  def show
    @stats = calculate_stats
    @selected = selected_id

    render 'index'
  end

  private
   
  def calculate_stats 
    if sub_stats == 'average_comments'
      Article.count.zero? ? 0 : Comment.count.to_f / Article.count
    else
      table.calculate(
        operator,
        column
      )
    end
  end
   
  def stats_params
    @stats_params ||= JSON.parse(params['stats'])
  end

  def sub_stats
    stats_params['sub_stats']
  end

  def table
    table_params = (stats_params['table'] || 'article').camelize.constantize
  end

  def operator
    stats_params['operator']
  end

  def column
    stats_params['column']
  end

  def selected_id
    (stats_params['id'] || "1").to_i
  end
end

app/controllers/welcom_controller.rb
class WelcomController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
  </p>

  <p>
  <%= form.label :text %><br>
  <%= form.text_area :text %>
  </p>

  <p>
  <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th><%= link_to 'Title', { sort: 'title' }  %></th>
    <th>Text</th>
    <th>Author</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.user.email.split('@').first %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
<strong>Commenter:</strong>
<%= comment.user.email %>
</p>

<p>
<strong>Comment:</strong>
<%= comment.body %>
</p>

<p>
<%= link_to 'Destroy Comment', [comment.article, comment],
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
  <%= form.label :body %><br>
  <%= form.text_area :body %>
  </p>
  <p>
  <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <hr>
    <%= yield %>
  </body>

  <footer>
    <hr>
    <%= link_to "Home", root_path %>
  </footer>
</html>

app/views/stats/index.html.erb
<h1>Listing Stats</h1>

<%= form_tag(stats_show_path, :method => :get) do %>
  <select name="stats">
    <option value='{"table":"article", "operator":"count", "column":"", "id":"1"}' <%= @selected == 1 ? 'selected' : '' %> >
      Total number of articles
    </option>
    <option value='{"table":"comment", "operator":"count", "column":"", "id":"2"}' <%= @selected == 2 ? 'selected' : '' %> >
      Total number of comments
    </option>
    <option value='{"sub_stats":"average_comments", "id":"3"}' <%= @selected == 3 ? 'selected' : '' %>>
      Average number of comments per article
    </option>
  </select>
  <%= submit_tag "GET" %>
<% end %>
<br/ >
<%= "Result: #{@stats}" %>

app/views/welcom/index.html.erb
<h1>Hello</h1>
<%= link_to 'Blog', controller: 'articles' %>
<br />
<%= link_to 'Interesting stats', controller: 'stats' %>
<br />
<%= link_to 'Manage your writing' %>